using HotelBookingDemo.Subjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Net;
using System.Net.Mail;

//we added a customer class with the idea of storing customer objects and object details into a database,
//however it was decided not to go ahead with using a database here
//as we wanted the observer pattern to be simple and easy to understand.
namespace HotelBookingDemo
{
    public class Customer : IObserver
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int NightsBooked { get; set; }

        public Customer(string n, string s, string a, string e, string p, int nB)
        {
            this.Name = n;
            this.Surname = s;
            this.Address = a;
            this.Email = e;
            this.Phone = p;
            this.NightsBooked = nB;
        }

        public override string ToString()
        {
            return base.ToString();
        }

        public void Update(ISubject subject)
        {
            if (subject is PromoCode promoCode)
            {
                try
                {
                    var senderEmail = new MailAddress("ENTER_YOUR_EMAIL_HERE", "Hotel Demo");
                    var receiverEmail = new MailAddress(Email);
                    var password = "ENTER_YOUR_PASSWORD_HERE";
                    var smtp = new SmtpClient
                    {
                        Host = "smtp.outlook.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(senderEmail.Address, password)
                    };
                    using
                        (var mess = new MailMessage(senderEmail, receiverEmail)
                        {
                            Subject = "New Promo Deal",
                            Body = "Dear " + Name + " " + Surname + ","
                                    + "\n\nWe have released a new promotional offer:\n"
                                    + promoCode.PromotionCode
                                    + "\n\nAvail of this deal on our app now!"
                                    + "\n\nRegards,"
                                    + "\nHotel Management."
                                    + "\n\n\n\nThis email has been automatically generated by an application."
                                    + "\nIt is intended for app demonstration purposes only."
                                    + "\nPlease contact " 
                                    + "ENTER_YOUR_EMAIL_HERE" 
                                    + " with any queries."
                        }
                        )
                    {
                        smtp.Send(mess);
                    }
                }
                catch
                {

                }
            }
        }
    }


}
